# Generated by Django 5.1.5 on 2025-07-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='books/pdfs/')),
                ('batch', models.CharField(choices=[('year1', 'الفرقة الأولى'), ('year2', 'الفرقة الثانية'), ('year3', 'الفرقة الثالثة'), ('year4', 'الفرقة الرابعة')], default='year1', max_length=10)),
            ],
            options={
                'indexes': [models.Index(fields=['title'], name='academic_bo_title_570e00_idx')],
            },
        ),
    ]
